### ISSUE TITLE
24 Hour Time

### ISSUE THREAD

**Issue by remlap** [mustaqimM/mpv-scripts#1]
Hi would like to make a suggestion and have this script display 24 hour time for show end time.

`currentHour = tonumber(os.date("%H"))`

Thanks.

**Comment by mustaqimM** [comment]
Incidentally I just now implemented it because I also wanted it, thanks :)


(Sorry for the delay, I didn't get any notification)

**Comment by remlap** [comment]
Excellent thanks.
