### ISSUE TITLE
Why add 1 to the ending hour?

### ISSUE THREAD

**Issue by ghost** [mustaqimM/mpv-scripts#4]
https://github.com/mustaqimM/mpv-scripts/blob/10d726edb9bc1166b9ad6757224fea3eded276e5/time.lua#L40

Play time: 01:24
System time: 23:29
Ending time: 01:53 (**1h off**)

![screenshot1](https://tknk.io/Dtzb)

Play time: 01:24
System time: 23:36
Ending time: 02:00 (**1h off**)

![screenshot2](https://tknk.io/sGW7)

Play time: 01:24
System time: 23:59
Ending time: 02:23 (**1h off**)

![screenshot3](https://tknk.io/1poy)

**Only from midnight onward, the ending time is correct**

Play time: 01:24
System time: 00:00
Ending time: 01:24 (**Correct time**)

![screenshot4](https://tknk.io/VNNX)

**Comment by ghost** [comment]
@mustaqimM Any thoughts on this?

**Comment by mustaqimM** [comment]
@megadr01d the +1 shouldn't be there. I just tried it now by decreasing the speed `[` and making it end past midnight and it's off by an hour.
 
I can't even remember why I put it there and didn't have an occasion where I tested that particular case.

sorry for not answering (it seems I'm not getting any notifications from this repo)

**Comment by ghost** [comment]
OK, thanks for confirming.
See if you have your "Watch" settings set to "Watching: Be notified of all conversations".
